//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 11 in 1 blocks
//     Style: dseg7bold
//     Size: 12pt
//     Bold: no
//     Italic: no
//     Memory usage: 247 bytes
//
//*****************************************************************************

const uint8_t g_pui8Dseg7bold12pt[] =
{
    //
    // The format of the font.
    //
    FONT_FMT_WIDE_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    5,

    //
    // The height of the font.
    //
    13,

    //
    // The baseline of the font.
    //
    12,

    //
    // The font codepage (CODEPAGE_UNICODE).
    //
    14, 0,

    //
    // The number of blocks of characters (1).
    //
    1, 0,

    //
    // Block header 0: Codepoints 0x30 - 0x3a
    //
    0x30, 0x00, 0x00, 0x00,
    0x0b, 0x00, 0x00, 0x00,
    0x14, 0x00, 0x00, 0x00,

    //
    // Block 0 Offsets: Codepoints 0x30 - 0x3a
    //
    0x2c, 0x00, 0x00, 0x00,   // Offset 44 (0x2c)
    0x41, 0x00, 0x00, 0x00,   // Offset 65 (0x41)
    0x4d, 0x00, 0x00, 0x00,   // Offset 77 (0x4d)
    0x5c, 0x00, 0x00, 0x00,   // Offset 92 (0x5c)
    0x6b, 0x00, 0x00, 0x00,   // Offset 107 (0x6b)
    0x7b, 0x00, 0x00, 0x00,   // Offset 123 (0x7b)
    0x8a, 0x00, 0x00, 0x00,   // Offset 138 (0x8a)
    0x9d, 0x00, 0x00, 0x00,   // Offset 157 (0x9d)
    0xae, 0x00, 0x00, 0x00,   // Offset 174 (0xae)
    0xc6, 0x00, 0x00, 0x00,   // Offset 198 (0xc6)
    0xda, 0x00, 0x00, 0x00,   // Offset 218 (0xda)

    //
    // Block 0 Data: Codepoints 0x30 - 0x3a
    //
     21,   7,  36,  33,  65,  17,  65,  17,  65,  17,  65, 241, 
     65,  17,  65,  17,  65,  17,  65,  36, 128,  12,   7, 161, 
     97,  97,  97, 209,  97,  97,  97, 240, 144,  15,   7,  36, 
    113,  97,  97,  97,  97,  36,  33,  97,  97,  97, 116, 128, 
     15,   7,  20, 113,  97,  97,  97,  97,  36, 113,  97,  97, 
     97,  36, 144,  16,   7, 241,  65,  17,  65,  17,  65,  17, 
     65,  36, 113,  97,  97,  97, 224,  15,   7,  36,  33,  97, 
     97,  97,  97, 116, 113,  97,  97,  97,  36, 128,  19,   7, 
     36,  33,  97,  97,  97,  97, 116,  33,  65,  17,  65,  17, 
     65,  17,  65,  36, 128,  17,   7,  36,  33,  65,  17,  65, 
     17,  65,  17,  65, 209,  97,  97,  97, 240,  96,  24,   7, 
     36,  33,  65,  17,  65,  17,  65,  17,  65,  17,  65,  36, 
     33,  65,  17,  65,  17,  65,  17,  65,  36, 128,  20,   7, 
     36,  33,  65,  17,  65,  17,  65,  17,  65,  17,  65,  36, 
    113,  97,  97,  97,  36, 128,   9,   7, 240, 146, 240, 240, 
     50, 240, 240, 
      0,   // Padding

};

tFont *g_psFontWDseg7bold12pt = (tFont *)g_pui8Dseg7bold12pt;
