//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 11 in 1 blocks
//     Style: monospace
//     Size: 6pt
//     Bold: no
//     Italic: no
//     Memory usage: 138 bytes
//
//*****************************************************************************

const uint8_t g_pui8Monospace6pt[] =
{
    //
    // The format of the font.
    //
    FONT_FMT_WIDE_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    2,

    //
    // The height of the font.
    //
    5,

    //
    // The baseline of the font.
    //
    4,

    //
    // The font codepage (CODEPAGE_UNICODE).
    //
    14, 0,

    //
    // The number of blocks of characters (1).
    //
    1, 0,

    //
    // Block header 0: Codepoints 0x30 - 0x3a
    //
    0x30, 0x00, 0x00, 0x00,
    0x0b, 0x00, 0x00, 0x00,
    0x14, 0x00, 0x00, 0x00,

    //
    // Block 0 Offsets: Codepoints 0x30 - 0x3a
    //
    0x2c, 0x00, 0x00, 0x00,   // Offset 44 (0x2c)
    0x33, 0x00, 0x00, 0x00,   // Offset 51 (0x33)
    0x3a, 0x00, 0x00, 0x00,   // Offset 58 (0x3a)
    0x42, 0x00, 0x00, 0x00,   // Offset 66 (0x42)
    0x49, 0x00, 0x00, 0x00,   // Offset 73 (0x49)
    0x50, 0x00, 0x00, 0x00,   // Offset 80 (0x50)
    0x57, 0x00, 0x00, 0x00,   // Offset 87 (0x57)
    0x5d, 0x00, 0x00, 0x00,   // Offset 93 (0x5d)
    0x63, 0x00, 0x00, 0x00,   // Offset 99 (0x63)
    0x6a, 0x00, 0x00, 0x00,   // Offset 106 (0x6a)
    0x71, 0x00, 0x00, 0x00,   // Offset 113 (0x71)

    //
    // Block 0 Data: Codepoints 0x30 - 0x3a
    //
      7,   3,   2,  17,  18,  19,  64,   7,   3,  17,  33,  33, 
     33,  64,   8,   3,  33,  33,  17,  17,  17,  48,   7,   3, 
     33,  17,  49,  17,  64,   7,   3,  33,  18,  18,  33,  48, 
      7,   3,   2,  18,  49,  17,  64,   6,   3,  66,  18,  18, 
     48,   6,   3,  33,  33,  17, 112,   7,   3,   2,  33,  17, 
     19,  64,   7,   3,   2,  17,  17,  18,  96,   5,   3,  65, 
     81,  64, 
      0,   0,   // Padding

};

tFont *g_psFontWMonospace6pt = (tFont *)g_pui8Monospace6pt;
