//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 11 in 1 blocks
//     Style: dseg7bold
//     Size: 10pt
//     Bold: no
//     Italic: no
//     Memory usage: 218 bytes
//
//*****************************************************************************

const uint8_t g_pui8Dseg7bold10pt[] =
{
    //
    // The format of the font.
    //
    FONT_FMT_WIDE_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    4,

    //
    // The height of the font.
    //
    11,

    //
    // The baseline of the font.
    //
    10,

    //
    // The font codepage (CODEPAGE_UNICODE).
    //
    14, 0,

    //
    // The number of blocks of characters (1).
    //
    1, 0,

    //
    // Block header 0: Codepoints 0x30 - 0x3a
    //
    0x30, 0x00, 0x00, 0x00,
    0x0b, 0x00, 0x00, 0x00,
    0x14, 0x00, 0x00, 0x00,

    //
    // Block 0 Offsets: Codepoints 0x30 - 0x3a
    //
    0x2c, 0x00, 0x00, 0x00,   // Offset 44 (0x2c)
    0x3d, 0x00, 0x00, 0x00,   // Offset 61 (0x3d)
    0x47, 0x00, 0x00, 0x00,   // Offset 71 (0x47)
    0x54, 0x00, 0x00, 0x00,   // Offset 84 (0x54)
    0x61, 0x00, 0x00, 0x00,   // Offset 97 (0x61)
    0x6e, 0x00, 0x00, 0x00,   // Offset 110 (0x6e)
    0x7b, 0x00, 0x00, 0x00,   // Offset 123 (0x7b)
    0x8b, 0x00, 0x00, 0x00,   // Offset 139 (0x8b)
    0x99, 0x00, 0x00, 0x00,   // Offset 153 (0x99)
    0xad, 0x00, 0x00, 0x00,   // Offset 173 (0xad)
    0xbe, 0x00, 0x00, 0x00,   // Offset 190 (0xbe)

    //
    // Block 0 Data: Codepoints 0x30 - 0x3a
    //
     17,   6,  35,  33,  49,  17,  49,  17,  49, 209,  49,  17, 
     49,  17,  49,  35, 112,  10,   6, 145,  81,  81, 177,  81, 
     81,  81, 224,  13,   6,  35,  97,  81,  81,  81,  35,  33, 
     81,  81,  99, 112,  13,   6,  35,  97,  81,  81,  81,  20, 
     97,  81,  81,  35, 112,  13,   6, 209,  49,  17,  49,  17, 
     49,  35,  97,  81,  81, 192,  13,   6,  35,  33,  81,  81, 
     81,  99,  97,  81,  81,  35, 112,  16,   6,  35,  33,  81, 
     81,  81,  99,  33,  49,  17,  49,  17,  49,  35, 112,  14, 
      6,  35,  33,  49,  17,  49,  17,  49, 177,  81,  81,  81, 
    192,  20,   6,  35,  33,  49,  17,  49,  17,  49,  17,  49, 
     35,  33,  49,  17,  49,  17,  49,  35, 112,  17,   6,  35, 
     33,  49,  17,  49,  17,  49,  17,  49,  35,  97,  81,  81, 
     35, 112,   8,   6, 240,  97, 240, 129, 240,  80, 
      0,   0,   // Padding

};

tFont *g_psFontWDseg7bold10pt = (tFont *)g_pui8Dseg7bold10pt;
